"""
tools/7_export_head.py
━━━━━━━━━━━━━━━━━━━━━━
Export the trained sklearn pipeline to C++ constants by folding the
StandardScaler into the logistic regression weights.

Math:
  z_i = (x_i - mean_i) / std_i           (scaler)
  logit = sum(w_i * z_i) + b             (logreg)
        = sum(w_i/std_i * x_i) + (b - sum(w_i * mean_i / std_i))
        = sum(W_i * x_i) + B             (folded)

This means C++ inference is a single dot product — zero library dependency.

Usage:
    cd solution/
    python tools/7_export_head.py

Input:   models/head.pkl
Output:  Prints exact C++ code to paste into include/config.hpp
         (Section 7: HEAD_WEIGHTS and HEAD_BIAS)
         Also writes models/head_cpp.txt as a reference copy.
"""

import numpy as np
import joblib
from pathlib import Path

def main():
    pkl_path = Path("models/head.pkl")
    if not pkl_path.exists():
        raise FileNotFoundError(f"{pkl_path} not found. Run 5_train_head.py first.")

    clf    = joblib.load(pkl_path)
    scaler = clf.named_steps["standardscaler"]
    lr     = clf.named_steps["logisticregression"]

    mean  = scaler.mean_
    scale = scaler.scale_
    w     = lr.coef_[0]
    b     = float(lr.intercept_[0])
    n     = len(w)

    # Fold scaler into weights
    W_folded = w / scale
    B_folded = b - float(np.sum(w * mean / scale))

   
    lines = []
    lines.append("// ─── Paste this block into include/config.hpp (Section 7) ───")
    lines.append("// Then set USE_LEARNED_HEAD = true and rebuild.")
    lines.append("//")
    lines.append("// Generated by tools/7_export_head.py")
    lines.append(f"// Number of features: {n}")
    lines.append("//")

    w_vals = ", ".join(f"{v:.8f}f" for v in W_folded)
    lines.append(f"inline const std::array<float, N_FEATURES> HEAD_WEIGHTS = {{")
    # Format nicely: 5 per line
    rows = [W_folded[i:i+5] for i in range(0, n, 5)]
    for row in rows:
        vals = "  " + ", ".join(f"{v:.8f}f" for v in row) + ","
        lines.append(vals)
    lines[-1] = lines[-1].rstrip(",")
    lines.append("};")
    lines.append(f"inline constexpr float HEAD_BIAS = {B_folded:.8f}f;")
    lines.append("inline constexpr bool  USE_LEARNED_HEAD = true;")
    lines.append("// ─────────────────────────────────────────────────────────")

    output = "\n".join(lines)

    print("\n" + "═" * 64)
    print("  COPY THE BLOCK BELOW INTO include/config.hpp  (Section 7)")
    print("═" * 64 + "\n")
    print(output)
    print("\n" + "═" * 64)


    txt_path = Path("models/head_cpp.txt")
    txt_path.write_text(output)
    print(f"\n[SAVED] Also written to {txt_path}")

    test_input = np.random.randn(1, n).astype(np.float32)
    orig_prob  = clf.predict_proba(test_input)[0][1]
    logit_fold = float(np.dot(W_folded, test_input[0]) + B_folded)
    fold_prob  = 1.0 / (1.0 + np.exp(-logit_fold))
    diff = abs(orig_prob - fold_prob)
    print(f"\n[VERIFY] Folded weight check — prob diff = {diff:.2e}  "
          f"({'PASS' if diff < 1e-5 else 'FAIL'})")

    print("\n[DONE]  Steps to complete:")
    print("  1. Paste the block above into include/config.hpp (replace Section 7)")
    print("  2. Verify USE_LEARNED_HEAD = true in config.hpp")
    print("  3. cd build && make -j$(nproc)")
    print("  4. ./build/oop_detect ../input ../output")


if __name__ == "__main__":
    main()
